services:
  postgres:
    image: postgres:17
    container_name: healayra-postgres

    environment:
      POSTGRES_DB: healayra
      POSTGRES_USER: healayra_user
      POSTGRES_PASSWORD: healayra_pass

    ports:
      - "5432:5432"

    volumes:
      - healayra_postgres_data:/var/lib/postgresql/data

volumes:
  healayra_postgres_data: