spring.application.name=healayra-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/healayra
spring.datasource.username=healayra_user
spring.datasource.password=healayra_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info